# Generated by Django 4.1.6 on 2023-02-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('unit_number', models.BigIntegerField(blank=True, null=True)),
                ('time_cycles', models.BigIntegerField(blank=True, null=True)),
                ('setting_1', models.FloatField(blank=True, null=True)),
                ('setting_2', models.FloatField(blank=True, null=True)),
                ('setting_3', models.FloatField(blank=True, null=True)),
                ('s_2', models.FloatField(blank=True, null=True)),
                ('s_3', models.FloatField(blank=True, null=True)),
                ('s_4', models.FloatField(blank=True, null=True)),
                ('s_7', models.FloatField(blank=True, null=True)),
                ('s_8', models.FloatField(blank=True, null=True)),
                ('s_9', models.FloatField(blank=True, null=True)),
                ('s_11', models.FloatField(blank=True, null=True)),
                ('s_12', models.FloatField(blank=True, null=True)),
                ('s_13', models.FloatField(blank=True, null=True)),
                ('s_14', models.FloatField(blank=True, null=True)),
                ('s_15', models.FloatField(blank=True, null=True)),
                ('s_17', models.FloatField(blank=True, null=True)),
                ('s_20', models.FloatField(blank=True, null=True)),
                ('s_21', models.FloatField(blank=True, null=True)),
                ('rul', models.BigIntegerField(blank=True, db_column='RUL', null=True)),
            ],
            options={
                'db_table': 'test_data',
                'managed': False,
            },
        ),
    ]
